[project]
name = "cls"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pyside6>=6.10.3",
    "simpleeval>=1.0.7",
    "sympy>=1.14.0",
]

[project.scripts]
cls = "app.main:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
namespace = true
module-name = "app"
module-root = "."
